[package]
name = "preipo_covered_call"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "preipo_covered_call"

[features]
default = []
no-entrypoint = []
cpi = ["no-entrypoint"]
no-idl = []
no-log-ix-name = []
anchor-debug = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = "=0.32.1"
anchor-spl = { version = "=0.32.1", default-features = false, features = ["token_2022", "associated_token"] }
