[package]
name = "parcel"
version = "0.1.0"
edition = "2021"
[lib]
crate-type = ["cdylib", "lib"]
name = "parcel"
[features]
default = ["custom-heap"]
no-entrypoint = []
cpi = ["no-entrypoint"]
no-idl = []
no-log-ix-name = []
anchor-debug = []
custom-heap = []
custom-panic = []
[dependencies]
anchor-lang = "=0.32.1"
anchor-spl = { version = "=0.32.1", default-features = false, features = ["token", "token_2022"] }
solana-sha256-hasher = "=2.3.0"
solana-program-entrypoint = "=2.3.0"
